### ISSUE TITLE
Compatibility to the Linux Datalink library by David Fries

### ISSUE THREAD

**Issue by l3ennji** [synthead/timex-datalink-arduino#13]
Hi,
I have been using the Linux Datalink library by David Fries (https://github.com/dfries/datalink_ironman) to sync my watches in the past. 
It supplies an application to send data provided by a datafile to a serial device and some code for a teensy board to control the led. Since the Teensy 3.+ boards won't be available anymore, I intended to switch to the 4.+ generation. The code supplied in the library unfortunately only works with the 3.+ generation and I wasn't able to update the code due to a lack of knowledge. So I tried using the timex arduino code in combination with the Teensy 4.+ and the Linux Datalink library datafile application. The code seems to run on the teensy 4.0, the internal LED lights up when serial data is received, but the timing seems to be an issue. I can not tell whether the timing is supplied by the sender or the receiver, as I do not fully understand the code and the concept behind it. (I understand the very basics with the data having to be transmitted at 60hz, sync bits, databits and so on, but do not understand how this is related to the baudrate of the transmission or the internal clock of the teensy or arduino board connected.)
Maybe it would be worth having a look at supporting the Linux Datalink library. I'll gladly offer any assistance and any help I can be of, although it might not be much.

Best regards

Benny

**Comment by synthead** [comment]
Hi @l3ennji! :wave: Thanks for filing this issue!

> I have been using the Linux Datalink library by David Fries (https://github.com/dfries/datalink_ironman) to sync my watches in the past.  It supplies an application to send data provided by a datafile to a serial device and some code for a teensy board to control the led.

Hey great!  This project aims to emulate a real Notebook Adapter as close as possible.  While working on the emulation, I sniffed UART data from various original Timex software on a Pentium MMX Windows 98SE machine with a real Notebook Adapter plugged into a physical RS232C port:

![IMG_20230221_031735](https://github.com/synthead/timex-datalink-arduino/assets/820984/07caab4f-4570-4afa-a0de-9e750dff9c36)

I did a bunch of testing and sniffing, and discovered that the original adapter uses hardware flow control:

![image](https://user-images.githubusercontent.com/820984/220234838-22c1f917-4742-4630-8425-23eaa8f70ab8.png)

Hardware flow control with USB serial is somewhat tricky.  With a real RS232C interface, you'd typically connect RTS and DTR pins to GPIO pins, but these signals are generally not available over USB serial.  The hardware flow control would typically help toggle the "command" and "data" modes on the Notebook Adapter, but I discovered that as long as the emulated adapter simply responds with the expected serial data, the software will still work.

However, I need to watch the data to determine when "transmit" packets are being sent so I can switch from the "command" mode to the "transmit" mode.  The "transmit" mode remains toggled until no data is received for 1 second.  After 1 second without data, it switches back to "command" mode by itself in preparation for another set of serial data.

https://github.com/synthead/timex-datalink-arduino/blob/4ed5af8231f9898d69d24336f3264deeb5005079/notebook_adapter.cpp#L17-L46

This is the only major functionality difference between the original adapter and the emulated one from this project.  I have verified that it works with every original Timex Datalink software suite, so as long as datalink_ironman is sending data that's compatible with the original adapter, it should "just work."

> Since the Teensy 3.+ boards won't be available anymore, I intended to switch to the 4.+ generation. The code supplied in the library unfortunately only works with the 3.+ generation and I wasn't able to update the code due to a lack of knowledge.

What problems did you run into with a Teensy 4 board?  Which 4.x board did you use?  Do you have an error log?  It's likely that you'll need to change GPIO pins, but other than that, it should still work.  This is a pretty simple project, really :slightly_smiling_face: 

> So I tried using the timex arduino code in combination with the Teensy 4.+ and the Linux Datalink library datafile application. The code seems to run on the teensy 4.0, the internal LED lights up when serial data is received, but the timing seems to be an issue. I can not tell whether the timing is supplied by the sender or the receiver, as I do not fully understand the code and the concept behind it. (I understand the very basics with the data having to be transmitted at 60hz, sync bits, databits and so on, but do not understand how this is related to the baudrate of the transmission or the internal clock of the teensy or arduino board connected.)

The timing is actually controlled by the client software!  This is Timex's design, and the adapter emulator follows the original spec for compatibility.  This means that there are no built-in sleep statements between bytes.  Even though this means that there are quite a few sleep statements on the client end, it gives the software a lot more control over timing, which can be fine-tuned to greatly quicken transfer rate.

I'm not sure what datalink_ironman is doing, but if it isn't adding sleep statements of its own between bytes and packets, then you probably won't have a successful transmission.  This is the byte and packet sleep times set on [the NotebookAdapter class in timex_datalink_client](https://github.com/synthead/timex_datalink_client/blob/aafcaf2e8020980758bef718e370415c5fd90583/lib/timex_datalink_client/notebook_adapter.rb#L7-L8):

```ruby
    BYTE_SLEEP_DEFAULT = 0.025
    PACKET_SLEEP_DEFAULT = 0.25
```

I've been able to reliably get the byte sleep time down to 0.008 and packet sleep down to 0.06 in my timex_datalink_client library.  See:

- https://github.com/synthead/timex_datalink_client/tree/main#tuning-data-transfer-performance

I also found that these sleep times can go much, much longer.  The transmission starts to fail after about a second between bytes.

> Maybe it would be worth having a look at supporting the Linux Datalink library. I'll gladly offer any assistance and any help I can be of, although it might not be much.

I'll take a look, although I'm less familiar with datalink_ironman :slightly_smiling_face: Is there any chance you have an original Notebook Adapter?  I have the suspicion that it won't work with the datalink_ironman software since this emulator doesn't work.

I wrote a library in Ruby that supports all features of all Datalink devices (all watches and more).  This library writes data to a Notebook Adapter, and the emulated and original adapter is both tested to work great.  Perhaps you wouldn't mind migrating to this lib?

- https://github.com/synthead/timex_datalink_client

**Comment by l3ennji** [comment]
Hi @synthead,

thank you very much for your interest and your detailed reply.
I'll try to add more information. 

`What problems did you run into with a Teensy 4 board? Which 4.x board did you use? Do you have an error log?`

My issue with the Teensy is not related to the code in this repository, but in the datalink_ironman software. It uses some libraries/code ("kinetis.h") which are not compatible with the Teensy 4 anymore, and I failed at converting the code to fit the new board. It just won't compile, and even if it compiles, it won't run. 
I have to add I have 0 experience with programming the Teensy Boards, I only used the documentation provided and my basic IT knowledge (having worked as a software engineer for special production lines and custom production machines, currently switching to programming excavators and large material handlers) to get the initial software to run on the hardware it was supposed to run on, I understand some/most of the syntax, but I lack the knowledge of the used libraries and dependencies. Also, it seems to be a (weird, at least to me, but it's probably very sophisticated, and I simply fail to see the beauty of it) mixture of plain C and C++ Code and isn't written in arduino. So I'm stuck on that end.

The Teensy Code in this repository seemed to run fine, but it won't work together with the data sent by the datalink_ironman library. The LED lights up, but stays on, and the data is also (I don't really know why yet) suddenly not sent correctly anymore. The same send code seems to slow down by a ton, writing to the Teensy 4 with the arduino code, compared to a teensy 3 with the correct datalink_ironman software. That's why I said I have no idea what the timing is actually based on.

What baudrate does the notebook adapter use? 9600? If the other on transmits at eg. 112500, that could be an issue.

`I'll take a look, although I'm less familiar with datalink_ironman 🙂 Is there any chance you have an original Notebook Adapter? I have the suspicion that it won't work with the datalink_ironman software since this emulator doesn't work.`

I do have an original adapter indeed, but it's still sealed in box and part of my (now actually pretty large) collection, and with the old teensy still working great, I never had the need to open it, and actually probably would hate to do so. I'm only looking into new alternatives, because I want to keep those watches running and fully functional for as long as possible, and only having one "smart" adapter and knowing I probably won't get a new one, I do what I have to do. And the Teensy 4 seemed to be the next best option. And you're probably right, it probably wouldn't work.

`I wrote a library in Ruby that supports all features of all Datalink devices (all watches and more). This library writes data to a Notebook Adapter, and the emulated and original adapter is both tested to work great. Perhaps you wouldn't mind migrating to this lib?`

My idea to kind of merge both softwares has a couple of different reasons.
Firstly, and most importantly, I'm lazy. The cost-benefit-ratio of migrating now, just to be safe in the future, all while still having a fully functional setup available, just seemed too high. 

Secondly, I don't know ruby, never worked with it, and would have to basically copy the parser for the datafile, which is used by the datalink_ironman application to supply data for the watch, to some kind of application which implements the ruby library. I'm not a great app developer, and it would cost me a ton of hours, probably. 
The result would probably be a native windows 10 app, though, which would be great, even though my solution using the linux subsystem for windows works great too, and is probably more independent.

I thought, maybe there was a simple way of getting those two softwares to run with each other with just little tweaks on the interface. As soon as I would get the data right, everything would be fine, but due to my limited knowledge, this seems very hard.

I also think, that it's probably more likely that the datalink_ironman software needs to be adapted, but I wanted to contact both ends of the line (I also posted an issue on the datalink_ironman-repo.) and maybe one would implicitly understand what the other one is doing, due to experience or being more familiar with the systems used. 

I'll try to run a couple of tests with a virtual comport to send the data to and hopefully get a more insightful output on what is actually going on.

I understand that this is not an actual issue and more or less a probably single interest for the sake of comfort and individual circumstances, but I still very much appreciate any help. I'll post results of the outputs as soon as I have any.

Thanks a lot.





Soooo....

This is what I wrote about 35mins ago.
I wanted to see how easy to use ruby would actually be, and lo and behold: It's a charm, I finally have the wrist apps, the Teensy 4 and his 3 spare companions run like a charm, I'm deeply ashamed now. 

(To save what's left of my honor: I really invested many weekends on trying to get this to run, but I obviously had a totally faulty understanding on what "library" was supposed to mean. Library always sounds like a horrible hastle and "I won't run on my own!" to me, but it handles like any other script. No need for a datafile, the ruby file is sufficient.)

If I'm allowed one last question before I retreat in shame and silence:
Is there a possibility to upload more than one wristapp? If I add more lines like the one in the example, the last wristapp seems to win.

Thanks so much for your impeccable work. Very well done.

All the best

Benny

**Comment by synthead** [comment]
> I wanted to see how easy to use ruby would actually be, and lo and behold: It's a charm, I finally have the wrist apps, the Teensy 4 and his 3 spare companions run like a charm

That's so great!  I'm really glad to hear that!  If you had any friction from using the lib to reading the docs, please don't hesitate to file an issue in case something could be better explained or otherwise improved :smile: 

> Is there a possibility to upload more than one wristapp? If I add more lines like the one in the example, the last wristapp seems to win.

Unfortunately, no, you can only put one WristApp on the 150 and 150s at a time.  The reason the "last one" gets loaded to the watch is because you're actually uploading a WristApp, then immediately uploading a second WristApp over the previous data.  This is a limitation of the watches themselves: there is only about 800-ish bytes of data for WristApps on the watch, and this data is shared with the sound theme.  So you may only have about 750 or so bytes available with a fancy sound theme!

If you want to see a really fancy WristApp, check this demo out!

![image](https://github.com/synthead/timex-datalink-arduino/assets/820984/2b2eeb03-e72e-42c0-bdc6-5befb83871bb)

- https://www.pouet.net/prod.php?which=87121

This demo uses more memory than the WristApp is capable of storing, so some of the data the WristApp reads from is in the EEPROM storage that is typically used for phone numbers, anniversaries, etc.  Due to this, you can't just upload a ZAP file, and the EEPROM data is custom for this purpose.  However, the author included a "bitstream" of the bytes that would be sent to a Notebook Adapter, so I managed to reverse engineer it to use it as bytes for this library:

```ruby
#!/usr/bin/env ruby

require "timex_datalink_client"

bitstream_file = File.open(ARGV[0], "rb")

packets = TimexDatalinkClient::Protocol3::Sync.new.packets

until bitstream_file.eof?
  length = bitstream_file.read(1).ord
  packets << [length] + bitstream_file.read(length - 1).bytes
end

notebook_adapter = TimexDatalinkClient::NotebookAdapter.new(
  serial_device: ARGV[1] || "/dev/ttyACM0",
  byte_sleep: 0.007,
  packet_sleep: 0.06,
  verbose: true
)

notebook_adapter.write(packets)
```

Use the above script like so:

```shell
./upload-bitstream watch150.bts /dev/ttyACM0
```

Thanks so much for all the kind words, and congrats on getting your WristApps uploaded!

**Comment by synthead** [comment]
Closing for now, but please don't hesitate to reopen or file a new issue if you have any questions!
